export const mockGames = [
    {
        id: 1,
        title: "ECHOES OF THE FUTURE",
        genre: ["Indie", "Fantacy"],
        description: "A hopeful sci-fi adventure where a team of explorers uncovers lost knowledge to save a dying world.Your choices shape the future as you journey through a beautiful, living city of tomorrow",
        price: "Coming Soon",
        releaseDate: "2026",
        image: "/covers/eco.jpeg",
        screenshots: [
            "/screenshots/eco-1.jpeg",
            "/screenshots/eco-2.jpeg",
            "/screenshots/eco-3.jpeg",
        ],
    },
    {
        id: 2,
        title: "ECHOES OF THE WARD",
        genre: ["Platformer", "Horror"],
        description: "Explore a war-scarred, abandoned hospital where survival depends on stealth, light, and listening to haunting echoes that reveal hidden threats.Solve environmental puzzles, evade unseen enemies, and uncover fragments of the past as every step risks awakening something watching from the dark.",
        price: "$9.99",
        releaseDate: "2025",
        image: "/covers/echos.jpeg",
        screenshots: [
            "/screenshots/av-1.jpeg",
            "/screenshots/av-2.jpeg",
            "/screenshots/av-3.jpeg",
        ],
    },
    {
        id: 3,
        title: "OPERATIVE FALLEN CITY",
        genre: ["Co-op", "FPS"],
        description: "Operative: Fallen City is a tactical modern-war shooter set in a devastated urban battlefield where every decision matters. Players take on the role of an elite operative, using stealth, squad commands, drones, and intense firefights to reclaim a city overrun by hostile forces.",
        price: "$10.99",
        releaseDate: "2026",
        image: "/covers/opr.jpeg",
        screenshots: [
            "/screenshots/opr-1.jpeg",
            "/screenshots/opr-2.jpeg",
            "/screenshots/opr-3.jpeg",
        ],
    },
    {
        id: 4,
        title: "RECLAIMED EARTH",
        genre: ["Survial", "Exploration"],
        description: "Reclaimed Earth is a survival exploration game where players must navigate a harsh, desolate world to survive and thrive. With limited resources, players must gather materials, build shelters, and fend off dangerous creatures as they journey through treacherous terrains and harsh climates.",
        price: "$6.99",
        releaseDate: "2025",
        image: "/covers/earth.jpeg",
        screenshots: [
            "/screenshots/rec-1.jpeg",
            "/screenshots/rec-2.jpeg",
            "/screenshots/rec-3.jpeg",
        ],
    },
    {
        id: 5,
        title: "GENZ",
        genre: ["Action", "Racing"],
        description: "Genz is an action-packed racing game where players control a sleek, futuristic vehicle through treacherous terrains. With precise controls, strategic upgrades, and intense challenges.",
        price: "$12.99",
        releaseDate: "2023",
        image: "/covers/genz.jpeg",
        screenshots: [
            "/screenshots/gen-2.jpeg",
            "/screenshots/gen-3.jpeg",
            "/screenshots/genz-4.jpeg",
        ],
    },
    {
        id: 6,
        title: "CURSE OF THE LOST ISLE",
        genre: ["Strategy", "Puzzle Solving"],
        description: "Curse of the Lost Isle is a strategy puzzle game where players navigate through treacherous islands, solve complex puzzles, and fend off relentless enemies. With strategic planning, resource management, and tactical combat, players must survive and thrive in a perilous world.",
        price: "$8.99",
        releaseDate: "2024",
        image: "/covers/curse.jpeg",
        screenshots: [
            "/screenshots/ap-1.jpeg",
            "/screenshots/ap-2.jpeg",
            "/screenshots/ap-3.jpeg",
        ],
    },
];
