export const mockGames = [
    {
        id: 1,
        title: "Glitch",
        genre: ["Indie", "Time Travel"],
        price: "Coming Soon",
        releaseDate: "2026",
        image: "/covers/glitch.jpeg",
    },
    {
        id: 2,
        title: "Shadows",
        genre: ["Platformer", "Adventure"],
        price: "$9.99",
        releaseDate: "2025",
        image: "/covers/shadows.jpeg",
    },
    {
        id: 3,
        title: "Spacewar",
        genre: ["Indie", "Adventure"],
        price: "$10.99",
        releaseDate: "2026",
        image: "/covers/spacewar.jpeg",
    },
    {
        id: 4,
        title: "Pixelvillage",
        genre: ["Pixel", "Exploration"],
        price: "$6.99",
        releaseDate: "2025",
        image: "/covers/pixelvillage.jpeg",
    },
    {
        id: 5,
        title: "Darkwar",
        genre: ["Action", "Horror"],
        price: "$12.99",
        releaseDate: "2023",
        image: "/covers/darkwar.jpeg",
    },
    {
        id: 6,
        title: "Swordfight",
        genre: ["Strategy", "Horror"],
        price: "$8.99",
        releaseDate: "2024",
        image: "/covers/swordfight.jpeg",
    },
];
